name: "Checkout LLVM"
description: "Checks out LLVM at the currently required/tested revision used to build Pylir"

runs:
  using: composite
  steps:
    - name: Checkout LLVM
      uses: actions/checkout@v3
      with:
        repository: llvm/llvm-project
        ref: 74b5dad5e944db21e56e6d81eb14f11891a741ab
        path: llvm-project
