name: Builds

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Builds:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows-2022, cxx_compiler: clang-cl, c_compiler: clang-cl, runtime_lib: "MultiThreaded" }
          - { os: windows-2022, cxx_compiler: clang-cl, c_compiler: clang-cl, runtime_lib: "MultiThreadedDebug" }
          - { os: windows-2022, cxx_compiler: clang++, c_compiler: clang }
          - { os: windows-2022, cxx_compiler: clang++, c_compiler: clang, sanitizer: "address,undefined" }
          - { os: ubuntu-22.04, cxx_compiler: clang++, c_compiler: clang }
          - { os: ubuntu-22.04, cxx_compiler: clang++, c_compiler: clang, shared_libs: "ON" }
          - { os: ubuntu-22.04, cxx_compiler: clang++, c_compiler: clang, sanitizer: "thread" }
          - { os: ubuntu-22.04, cxx_compiler: clang++, c_compiler: clang, sanitizer: "address,undefined" }
          - { os: ubuntu-22.04, cxx_compiler: g++-10, c_compiler: gcc-10 }
          - { os: macos-12, cxx_compiler: clang++, c_compiler: clang }

    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout Pylir
        uses: actions/checkout@v3
        with:
          path: Pylir

      - name: Calculate ccache key
        id: ccache-key
        shell: pwsh
        run: |
          $key = '${{runner.os}}'

          if ('${{matrix.sanitizer}}') {
            $key += '-${{matrix.sanitizer}}'.Replace(',', '_and_')
          }

          if ('${{matrix.runtime_lib}}') {
            $key += '${{matrix.runtime_lib}}'
          }
          
          if ('${{matrix.shared_libs}}') {
            $key += '-shared'
          }

          "key=$key" >> $Env:GITHUB_OUTPUT

      - name: Install Dependencies
        id: dep-install
        uses: ./Pylir/.github/actions/dependencies
        with:
          cxx-compiler: ${{matrix.cxx_compiler}}
          ccache-key: ${{steps.ccache-key.outputs.key}}

      - name: Install Python depends
        run: |
          Invoke-expression "$Env:pythonLocation\python -m pip install -r ${{github.workspace}}/Pylir/test/requirements.txt"

      - name: Build LLVM
        id: llvm-build
        uses: ./Pylir/.github/actions/llvm-build
        with:
          c-compiler: ${{matrix.c_compiler}}
          cpp-compiler: ${{matrix.cxx_compiler}}
          sanitizers: ${{matrix.sanitizer}}
          runtime_lib: ${{matrix.runtime_lib}}
          shared_libs: ${{matrix.shared_libs}}
          cache-key: LLVM-${{steps.dep-install.outputs.key}}

      - name: Configure Pylir
        run: |
          $sanitizer_arg = ''
          if ('${{matrix.sanitizer}}') {
            $sanitizer_arg = '-DPYLIR_SANITIZER="${{matrix.sanitizer}}" -DCMAKE_CXX_FLAGS="-g1"'
          }
          $runtime_arg = ''
          if ('${{matrix.runtime_lib}}') {
            $runtime_arg = '-DCMAKE_MSVC_RUNTIME_LIBRARY=${{matrix.runtime_lib}}'
          }
          $shared_libs = ''
          if ('${{matrix.shared_libs}}') {
            $shared_libs = '-DBUILD_SHARED_LIBS=ON'
          }
          $use_lld = ''
          if (!$IsMacOs) {
            $use_lld = '-DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld"'
          }
          
          cmake -GNinja -Bpylir-build `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}} `
            -DCMAKE_C_COMPILER=${{matrix.c_compiler}} `
            $sanitizer_arg `
            $runtime_arg `
            $shared_libs `
            -DPython3_ROOT_DIR="$Env:pythonLocation" -DPython3_FIND_STRATEGY=LOCATION `
            -DCMAKE_C_COMPILER_LAUNCHER=ccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache `
            $use_lld `
            -DPYLIR_ENABLE_ASSERTIONS=ON `
            -DLLVM_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/llvm/" `
            -DMLIR_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/mlir/" `
            -DLLD_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/lld/" `
            -S ${{github.workspace}}/Pylir

      - name: Build Pylir
        run: |
          cmake --build pylir-build

      - name: Test
        working-directory: ${{github.workspace}}/pylir-build
        run: ctest --extra-verbose

      - name: Cleanup disk space
        if: always()
        run: |
          Remove-Item -Recurse -Force pylir-build -ErrorAction Ignore

