name: LLVM Cron

permissions:
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  llvm-cron:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows-2022, cpp-compiler: clang-cl, c-compiler: clang-cl, runtime_lib: "MultiThreaded" }
          - { os: windows-2022, cpp-compiler: clang-cl, c-compiler: clang-cl, runtime_lib: "MultiThreadedDebug" }
          - { os: windows-2022, cpp-compiler: clang++, c-compiler: clang }
          - { os: windows-2022, cpp-compiler: clang++, c-compiler: clang, sanitizers: "address,undefined" }
          - { os: ubuntu-22.04, cpp-compiler: clang++, c-compiler: clang }
          - { os: ubuntu-22.04, cpp-compiler: clang++, c-compiler: clang, shared_libs: "ON" }
          - { os: ubuntu-22.04, cpp-compiler: clang++, c-compiler: clang, sanitizers: "thread" }
          - { os: ubuntu-22.04, cpp-compiler: clang++, c-compiler: clang, sanitizers: "address,undefined" }
          - { os: ubuntu-22.04, cpp-compiler: g++-10, c-compiler: gcc-10 }
          - { os: macos-12, cpp-compiler: clang++, c-compiler: clang }
    uses: ./.github/workflows/llvm-build.yml
    with:
      os: ${{matrix.os}}
      c-compiler: ${{matrix.c-compiler}}
      cpp-compiler: ${{matrix.cpp-compiler}}
      sanitizers: ${{matrix.sanitizers}}
      runtime_lib: ${{matrix.runtime_lib}}
      shared_libs: ${{matrix.shared_libs}}
