name: Deploy to GitHub Pages

on:
  workflow_run:
    types: [ completed ]
    workflows: [ "Builds" ]
    #branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: pwsh

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Fetch Website
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "Build"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{github.workspace}}/pylir-build/docs/build

      - name: Deploy to GitHub Pages
        id: deployment
        run: ls
        # uses: actions/deploy-pages@v1

