name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  windows-build:
    runs-on: windows-2022

    steps:

      - name: Install Ninja
        uses: ashutoshvarma/setup-ninja@v1.1

      - name: Checkout Pylir
        uses: actions/checkout@v3
        with:
          path: Pylir

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Use developer command prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Python depends
        run: |
          Invoke-expression "$Env:pythonLocation\python -m pip install -r ${{github.workspace}}/Pylir/test/requirements.txt"

      - name: Install CCache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          ccache_options: |
            max_size: 2G
          override_cache_key: ${{runner.os}}
          windows_compile_environment: msvc

      - name: Checkout LLVM
        uses: ./Pylir/.github/actions/llvm-checkout

      - name: Configure LLVM Optimized TableGen
        run: |
          cmake -GNinja -Bllvm-optimized-tblgen `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_CXX_COMPILER=cl `
            -DCMAKE_C_COMPILER=cl `
            -DLLVM_CCACHE_BUILD=ON `
            -DLLVM_ENABLE_PROJECTS="mlir" `
            -DLLVM_TARGETS_TO_BUILD=host `
            -DLLVM_ENABLE_LLD=ON `
            -DPython3_EXECUTABLE="$Env:pythonLocation/python" `
            -S ${{github.workspace}}/llvm-project/llvm

      - name: Build LLVM Optimized TableGen
        run: |
          cmake --build llvm-optimized-tblgen --target mlir-tblgen llvm-tblgen mlir-linalg-ods-yaml-gen

      - name: Configure LLVM
        run: |
          $work_space = "${{github.workspace}}".replace('\', '/')
          cmake -GNinja -Bllvm-build `
            -DLLVM_TABLEGEN="$work_space/llvm-optimized-tblgen/bin/llvm-tblgen.exe" `
            -DMLIR_TABLEGEN="$work_space/llvm-optimized-tblgen/bin/mlir-tblgen.exe" `
            -DMLIR_LINALG_ODS_YAML_GEN="$work_space/llvm-optimized-tblgen/bin/mlir-linalg-ods-yaml-gen.exe" `
            -DCMAKE_BUILD_TYPE=Release `
            -DLLVM_USE_CRT_RELEASE=MTd `
            -DCMAKE_CXX_COMPILER=cl `
            -DCMAKE_C_COMPILER=cl `
            -DLLVM_CCACHE_BUILD=ON `
            -DLLVM_ENABLE_ASSERTIONS=ON `
            -DLLVM_ENABLE_PROJECTS="mlir;lld" `
            -DLLVM_TARGETS_TO_BUILD=host `
            -DLLVM_ENABLE_LLD=ON `
            -DPython3_EXECUTABLE="$Env:pythonLocation/python" `
            -S ${{github.workspace}}/llvm-project/llvm

      - name: Build LLVM
        run: |
          cmake --build llvm-build

      - name: Configure Pylir
        run: |
          cmake -GNinja -Bpylir-build `
            -DCMAKE_BUILD_TYPE=Release `
            -DPYLIR_EMBED_LLD=ON `
            -DCMAKE_CXX_COMPILER=clang-cl `
            -DCMAKE_C_COMPILER=clang-cl `
            -DPython3_EXECUTABLE="$Env:pythonLocation/python" `
            -DPYLIR_ENABLE_ASSERTIONS=ON `
            -DCMAKE_LINKER=link `
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDebug `
            -DLLVM_DIR="${{github.workspace}}/llvm-build/lib/cmake/llvm/" `
            -DMLIR_DIR="${{github.workspace}}/llvm-build/lib/cmake/mlir/" `
            -DLLD_DIR="${{github.workspace}}/llvm-build/lib/cmake/lld/" `
            -S ${{github.workspace}}/Pylir

      - name: Build Pylir
        run: |
          cmake --build pylir-build

      - name: Test
        working-directory: ${{github.workspace}}/pylir-build
        run: ctest --extra-verbose

