name: Windows

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  msvc-build:
    runs-on: windows-2022
    strategy:
      matrix:
        runtime_lib: [ "MultiThreadedDebug", "MultiThreaded" ]

    steps:

      - name: Install Ninja
        uses: ashutoshvarma/setup-ninja@v1.1

      - name: Checkout Pylir
        uses: actions/checkout@v3
        with:
          path: Pylir

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Use developer command prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Python depends
        run: |
          Invoke-expression "$Env:pythonLocation\python -m pip install -r ${{github.workspace}}/Pylir/test/requirements.txt"

      - name: Install CCache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          ccache_options: |
            max_size=0.5G
          override_cache_key: ${{runner.os}}-${{matrix.runtime_lib}}-msvc
          windows_compile_environment: msvc

      - name: Build LLVM
        id: llvm-build
        uses: ./Pylir/.github/actions/llvm-build
        with:
          c-compiler: cl
          cpp-compiler: cl
          runtime_lib: ${{matrix.runtime_lib}}

      - name: Configure Pylir
        run: |
          cmake -GNinja -Bpylir-build `
            -DCMAKE_BUILD_TYPE=Release `
            -DPYLIR_EMBED_LLD=ON `
            -DCMAKE_CXX_COMPILER=clang-cl `
            -DCMAKE_C_COMPILER=clang-cl `
            -DPython3_ROOT_DIR="$Env:pythonLocation" -DPython3_FIND_STRATEGY=LOCATION `
            -DPYLIR_ENABLE_ASSERTIONS=ON `
            -DCMAKE_LINKER=link `
            -DCMAKE_MSVC_RUNTIME_LIBRARY=${{matrix.runtime_lib}} `
            -DLLVM_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/llvm/" `
            -DMLIR_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/mlir/" `
            -DLLD_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/lld/" `
            -S ${{github.workspace}}/Pylir

      - name: Build Pylir
        run: |
          cmake --build pylir-build

      - name: Test
        working-directory: ${{github.workspace}}/pylir-build
        run: ctest --extra-verbose

  mingw-build:
    runs-on: windows-2022
    strategy:
      matrix:
        sanitizer: [ "address,undefined", "" ]

    steps:
      - name: Install Ninja
        uses: ashutoshvarma/setup-ninja@v1.1

      - name: Checkout Pylir
        uses: actions/checkout@v3
        with:
          path: Pylir

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          update: true
          pacboy: >-
            toolchain:p
          location: D:\
            
      - name: Prepend Msys2 to path
        run: echo "D:\msys64\clang64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Install Python depends
        run: |
          Invoke-expression "$Env:pythonLocation\python -m pip install -r ${{github.workspace}}/Pylir/test/requirements.txt"

      # See https://github.com/actions/cache/issues/53
      - name: Sanitize key
        id: sanitize-key
        run: |
          "key=$( '${{matrix.sanitizer}}'.Replace(',', '_and_') )" >> $Env:GITHUB_OUTPUT

      - name: Calculate cache size
        id: cache-size
        shell: pwsh
        run: |
          if ('${{matrix.sanitizer}}') {
             "size=1.5G" >> $Env:GITHUB_OUTPUT
          } else {
             "size=0.5G" >> $Env:GITHUB_OUTPUT
          }

      - name: Install CCache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          ccache_options: |
            max_size=${{steps.cache-size.outputs.size}}
          override_cache_key: ${{runner.os}}-${{steps.sanitize-key.outputs.key}}-clang64
          # Lying here because I am not running within msys2
          windows_compile_environment: msvc

      - name: Build LLVM
        id: llvm-build
        uses: ./Pylir/.github/actions/llvm-build
        with:
          c-compiler: clang
          cpp-compiler: clang++
          sanitizers: ${{matrix.sanitizer}}

      - name: Configure Pylir
        run: |
          $sanitizer_arg = ''
          if ('${{matrix.sanitizer}}') {
            $sanitizer_arg = '-DPYLIR_SANITIZER="${{matrix.sanitizer}}"'
          }
          cmake -GNinja -Bpylir-build `
            -DCMAKE_BUILD_TYPE=Release `
            -DPYLIR_EMBED_LLD=ON `
            -DCMAKE_CXX_COMPILER=clang++ `
            -DCMAKE_C_COMPILER=clang `
            $sanitizer_arg `
            -DPYLIR_DEFAULT_SYSROOT="D:/msys64/clang64" `
            -DPython3_ROOT_DIR="$Env:pythonLocation" -DPython3_FIND_STRATEGY=LOCATION `
            -DCMAKE_C_COMPILER_LAUNCHER=ccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache `
            -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" `
            -DPYLIR_ENABLE_ASSERTIONS=ON `
            -DLLVM_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/llvm/" `
            -DMLIR_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/mlir/" `
            -DLLD_DIR="${{steps.llvm-build.outputs.install-dir}}/lib/cmake/lld/" `
            -S ${{github.workspace}}/Pylir

      - name: Build Pylir
        run: |
          cmake --build pylir-build

      - name: Test
        working-directory: ${{github.workspace}}/pylir-build
        run: ctest --extra-verbose

      - name: Cleanup disk space
        run: |
          Remove-Item -Recurse -Force llvm-optimized-tblgen
          Remove-Item -Recurse -Force llvm-build
          Remove-Item -Recurse -Force pylir-build
